package com.belatrix.apadea.datamodel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.belatrix.apadea.datamodel.User;
import com.belatrix.apadea.datamodel.Session;
import com.belatrix.apadea.datamodel.Log;

import com.belatrix.apadea.datamodel.UserDao;
import com.belatrix.apadea.datamodel.SessionDao;
import com.belatrix.apadea.datamodel.LogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig logDaoConfig;

    private final UserDao userDao;
    private final SessionDao sessionDao;
    private final LogDao logDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        logDaoConfig = daoConfigMap.get(LogDao.class).clone();
        logDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        logDao = new LogDao(logDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Session.class, sessionDao);
        registerDao(Log.class, logDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
        logDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public LogDao getLogDao() {
        return logDao;
    }

}
