package com.belatrix.apadea.datamodel;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOG.
 */
public class Log {

    private Long id;
    private String CurrentLevel;
    private String Result;
    private String Observations;
    private long sessionId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, String CurrentLevel, String Result, String Observations, long sessionId) {
        this.id = id;
        this.CurrentLevel = CurrentLevel;
        this.Result = Result;
        this.Observations = Observations;
        this.sessionId = sessionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCurrentLevel() {
        return CurrentLevel;
    }

    public void setCurrentLevel(String CurrentLevel) {
        this.CurrentLevel = CurrentLevel;
    }

    public String getResult() {
        return Result;
    }

    public void setResult(String Result) {
        this.Result = Result;
    }

    public String getObservations() {
        return Observations;
    }

    public void setObservations(String Observations) {
        this.Observations = Observations;
    }

    public long getSessionId() {
        return sessionId;
    }

    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
