package com.belatrix.apadea.datamodel;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String FirstName;
    private String LastName;
    private Integer Age;
    private String Gender;
    private String Type;
    private String Avatar;
    private byte[] ProfileImage;

    // KEEP FIELDS - put your custom fields here
    public static final String USER_TYPE_TERAPEUTA = "therapist";
    public static final String USER_TYPE_SUBJECT = "subject";
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String FirstName, String LastName, Integer Age, String Gender, String Type, String Avatar, byte[] ProfileImage) {
        this.id = id;
        this.FirstName = FirstName;
        this.LastName = LastName;
        this.Age = Age;
        this.Gender = Gender;
        this.Type = Type;
        this.Avatar = Avatar;
        this.ProfileImage = ProfileImage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public Integer getAge() {
        return Age;
    }

    public void setAge(Integer Age) {
        this.Age = Age;
    }

    public String getGender() {
        return Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getAvatar() {
        return Avatar;
    }

    public void setAvatar(String Avatar) {
        this.Avatar = Avatar;
    }

    public byte[] getProfileImage() {
        return ProfileImage;
    }

    public void setProfileImage(byte[] ProfileImage) {
        this.ProfileImage = ProfileImage;
    }

    // KEEP METHODS - put your custom methods here

    public String getCompleteName() {
        return FirstName + " " + LastName;
    }
    // KEEP METHODS END

}
